# fly.toml app configuration file generated for stock-picker-still-water-9392 on 2025-12-23T23:47:24+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stock-picker-still-water-9392'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[env]
  TZ = 'Asia/Kolkata'

[processes]
  app = './stock-picker'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
